name: Build
on: [ push, pull_request, workflow_dispatch ]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghidra:
          - !!str "12.0"

    steps:
      - name: Clone Repository
        uses: actions/checkout@v6

      - name: Install Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Install Ghidra ${{ matrix.ghidra }}
        uses: antoniovazquezblanco/setup-ghidra@v2.0.17
        with:
          auth_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ matrix.ghidra }}

      - name: Build
        run: mvn clean package

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: GhidraGPT_Ghidra_${{ matrix.ghidra }}
          path: target/*.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v7

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: GhidraGPT_Ghidra_*/*.zip
